modLoader = "javafml"
loaderVersion = "${dep.forge_loader_version_range}"
license = "${mod.license}"
# issueTrackerURL="https://github.com/Git-Parcel/Mod/issues"
#clientSideOnly=false
[[mods]]
modId = "${mod.id}"
version = "${mod.version}"
displayName = "${mod.name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
# displayURL="https://github.com/Git-Parcel/Mod" # displayed in the mod UI
logoFile = "${mod.id}.png"
credits = "${mod.credits}"
authors = "${mod.author}"
description = '''${mod.description}'''
[[dependencies.${ mod.id }]]
modId = "forge"
mandatory = true
versionRange = "[${dep.forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod.id }]]
modId = "minecraft"
mandatory = true
versionRange = "${mod.minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
