modLoader = "javafml"
loaderVersion = "*"
license = "${license}"
issueTrackerURL = "${issues_url}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''${description}'''
logoFile = "${logo_file}"
logoBlur = false

[[mixins]]
config = "${id}.mixins.json"
[[mixins]]
config = "${id}.neoforge.mixins.json"

[[dependencies.${ id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ id }]]
modId = "system_storage_lib"
mandatory = true
versionRange = "[${system_storage_lib_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.${ id }]]
modId = "modernui"
mandatory = true
versionRange = "[${modernui_version},)"
ordering = "NONE"
side = "CLIENT"
